# Generated by Django 3.2.15 on 2022-09-13 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombook',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 16, 36, 12, 789513, tzinfo=utc)),
        ),
    ]
