# Generated by Django 3.2.15 on 2022-09-13 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_alter_roombook_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='days',
        ),
        migrations.AlterField(
            model_name='roombook',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 16, 53, 16, 660573, tzinfo=utc)),
        ),
    ]
