# Generated by Django 3.2.5 on 2022-07-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_hotels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotels',
            new_name='Hotel',
        ),
    ]
