# Generated by Django 3.2.5 on 2022-07-07 09:20

import api_v1.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_rename_hotels_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rooms', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('price', models.FloatField()),
                ('days', models.IntegerField()),
                ('photo', models.ImageField(default='no-photo.jpg', upload_to=api_v1.models.photo_path)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(default='no-photo.jpg', upload_to=api_v1.models.photo_path),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(api_v1.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoomBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=datetime.datetime(2022, 7, 8, 9, 20, 19, 963614, tzinfo=utc))),
                ('title', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('days', models.IntegerField()),
                ('cost', models.FloatField()),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.room')),
                ('user', models.ForeignKey(on_delete=models.SET(api_v1.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(api_v1.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
