# Generated by Django 3.2.5 on 2022-07-07 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_auto_20220707_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombook',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 9, 29, 23, 483677, tzinfo=utc)),
        ),
    ]
