# Generated by Django 3.2.5 on 2022-07-24 08:19

import api_v1.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_alter_roombook_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='averageCost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='averageRating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, default='no-photo.jpg', null=True, upload_to=api_v1.models.photo_path),
        ),
        migrations.AlterField(
            model_name='roombook',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 8, 19, 45, 598544, tzinfo=utc)),
        ),
    ]
